### ISSUE TITLE
disable catch-up?

### ISSUE THREAD

**Issue by lkb2k** [agenda/agenda#116]
Is there a way to disable the catch-up behavior for a job?  

Say for a job scheduled to run every 10 minutes, if the mongodb is unreachable for a period, when it comes back agenda seems to immediately run all the executions of the job that would have happened while it was gone.

For general maintenance tasks rather than catching up, i'd rather the schedule just picked up again and the task only ran once.  Otherwise for system intensive tasks I could overly stress the system as soon as the db becomes reachable again.

Is there a way to flag a job to not catch up?

**Comment by OmgImAlexis** [comment]
@rschmukler can you confirm the bug was fixed in ae34a240a2a7bf01c6bdf5196d8216860a20054d if it was please close.

**Comment by simison** [comment]
@OmgImAlexis note his https://github.com/agenda/agenda/commit/ae34a240a2a7bf01c6bdf5196d8216860a20054d#commitcomment-8803094:
>I actually found this bug while tracing down the issue mentioned in [#116](https://github.com/agenda/agenda/issues/116). While this doesn't solve that, it was a bug that I noticed while I debugged it.
>
>Basically, if a job already existed in the database, and was defined by `every` it would run 2x at start of agenda. This is because the lock would not be set when agenda was looking for new jobs.

Seems like it wasn't fixed.

If someone could write a repeatable script or a PR a test case for this, it would be a good starting point!
