### ISSUE TITLE
typing issue

### ISSUE THREAD

**Issue by bwgjoseph** [agenda/agenda#1266]
Hi,

I am trying out `agenda` but facing with types issue hence, unable to proceed. Could be related to #1218, and #1265 

The example usage of initializing `agenda` is `const agenda = new Agenda({ db: { address: mongoConnectionString } });`. However, the typing does not match what is in the docs.

```js
const agenda = new Agenda({
  db: {
    address: 'mongodb://...',
  },
});
```

https://github.com/agenda/agenda/blob/adc22b8b662e6e59364cf6bb4f2518e00606e482/lib/agenda/index.ts#L36-L51

The definition is as such, and since `db.collection` and `db.options` are not declared as optional (?), it will throw type error like such

```
Type '{ address: string; }' is missing the following properties from type '{ address: string; collection: string; options: MongoClientOptions; }': collection, options
```

---

The 2nd issue is the constructor error

```js
TypeError: agenda_1.Agenda is not a constructor
    at Object.<anonymous> (Z:\scheduler-service\src\agenda.ts:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (Z:\scheduler-service\node_modules\source-map-support\source-map-support.js:547:25)
    at Module.m._compile (C:\Users\Joseph\AppData\Local\Temp\ts-node-dev-hook-769800944806712.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at require.extensions.<computed> (C:\Users\Joseph\AppData\Local\Temp\ts-node-dev-hook-769800944806712.js:71:20)
    at Object.nodeDevHook [as .ts] (Z:\scheduler-service\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[ERROR] 01:02:28 TypeError: agenda_1.Agenda is not a constructor
```

Using `agenda: 4.1.0` and `typescript: 4.1.5`

**Comment by royibernthal** [comment]
Joining the issue.

I'll add that the typings of agenda.every and agenda.schedule are incorrect as well.
There are possibly other mistakes.

Need to redo the typings and actually test them :)

**Comment by BonnieMilian** [comment]
Joining the issue too, not able to start the agenda because of that error.
`agenda_1.Agenda is not a constructor`

**Comment by royibernthal** [comment]
As a temporary solution, this older version coupled with the deprecated typings seems to be working fine for me:
```
"agenda": "^3.1.0"
"@types/agenda": "^2.0.8"
```

**Comment by BonnieMilian** [comment]
Thanks I will try

**Comment by IglanCardeal** [comment]
Using:

```
"agenda": "^3.1.0"
"@types/agenda": "^2.0.8"
```

I got a warning:

>agenda > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

Do you think it's safe to use temporarily?

Just be advised to this warning.

**Comment by koresar** [comment]
Agenda 4.1.2 was just released. Here are the exports: https://unpkg.com/browse/agenda@4.1.2/dist/index.d.ts
Should be good for all the mentioned issues.
Please report any bugs and submit PRs if possible. :)

**Comment by oblank** [comment]
this issue not fixed
Agenda 4.1.2

**Comment by oblank** [comment]
```
const {Agenda} = require('agenda');
```
require agenda like this, and it works fine for me

**Comment by koresar** [comment]
Sorry about that. We need better unit tests.

**Comment by gopi2099** [comment]
if I require Like this **const {Agenda} = require('agenda');** today it is throwing error

**Comment by sulaysumaria** [comment]
I can confirm this works with node `14.16.0` and agenda `4.1.2`. Faced this issue today after updating from `4.1.0` to `4.1.2`.

```js
import { Agenda } from 'agenda';
```

**Comment by mrcranky** [comment]
> I can confirm this works with node `14.16.0` and agenda `4.1.2`. Faced this issue today after updating from `4.1.0` to `4.1.2`.
> 
> ```js
> import { Agenda } from 'agenda';
> ```

This would essential be a breaking change to the interface though, right? So is the intent that the change will be rolled back (and the default export will return to being the Agenda class), or is this now the recommended way of instantiating the class now and the documentation will be changed to match?

**Comment by koresar** [comment]
@leonardlin @simllll @simison gents, we need to show responsibility on making that breaking change unannounced. And decide what to do.

I, personally, do not have preferences here. I'd rather listen to what people suggest.

**Comment by leonardlin** [comment]
@koresar @simison @simllll I'm not sure if I get all the issue-threads 100%, but why can't we change the type exports back to how it used to be?
Make Agenda default export?
Would that fix it all?
Perhaps we can copy the types from the @types/agenda vs 2.x
I have been using those so far.

**Comment by simllll** [comment]
removing all other exports would kinda solve this, to get the "old" behaviour back we would need to export it via:

lib/index.ts must look like this:

```
import { Agenda } from "./agenda";
module.exports = Agenda;

```

no other exports are allowed in this case, the problem is then: Agenda will not work correctly with module imports anymore. To overcome this, we could add another "entrypoint". e.g. agenda/es.

I'll create a PR to show you what I mean. The problem with this approach would be furthermore that everyone who has changed their imports to  { Agenda } will stop working again, and they would either need to require('agenda') again direclty:
for non js:
`const Agenda = require('agenda');`
 
or for typescript:
`import Agenda from 'agenda/es'`

**Comment by thiagomagro** [comment]
You can use:
const { Agenda } = require('agenda')

**Comment by muhdshafiqsofian** [comment]
> ```
> const {Agenda} = require('agenda');
> ```
> 
> require agenda like this, and it works fine for me

This works for me. Thanks!

**Comment by mrcranky** [comment]
> I'll create a PR to show you what I mean. The problem with this approach would be furthermore that everyone who has changed their imports to { Agenda } will stop working again, and they would either need to require('agenda') again direclty:

I think the subsequent replies to this issue show that the longer this goes unpatched, the more painful it's going to be to go back to the old behaviour, because more people will have applied the fix that compensates for the behaviour change.

I don't have a particular preference and obviously the fix is easy, it's just _unexpected_ when you have npm set to not take major version updates for the module. I have agenda in use across a bunch of projects and have pinned it back to 4.1.0 rather than make fixes to all those projects I think I might have to roll back. I think it wouldn't be unreasonable to make a 4.1.3 that reverts to the old behaviour (even if it means losing typescript/import functionality), and immediately make a 5.0.0 that works the same way 4.1.2 does. That way users who blindly `npm update` won't find their code breaks, anyone who updated to 4.1.1/4.1.2 can update to 4.1.3 to fix the break; anyone who has applied the fix already will have the choice of rolling back their fix to use 4.1.3, or taking the major version update if they prefer the new interface.

**Comment by koresar** [comment]
Hi @mrcranky and others.

I am one of the lead maintainers here. I know all the pains of breaking changes in a PATCH release. I'm going through them monthly for the last 8 years.

I'd like to apologise for this silly situation when we had no single responsible person for the TS migration. This was a team effort with all the upside and downside of it. We all learnt the mistake. I hope everyone learnt from it.

With this PR https://github.com/agenda/agenda/pull/1298/files we are going to ensure few things: 
* This works: `const Agenda = require("agenda");`
* This works too: `const { Agenda } = require("agenda");`
* This works in TS: `import Agenda from "agenda";`
* This works in TS too: `import { Agenda } from "agenda";`
* I wrote unit test to make sure this doesn't break again in Agenda v4.
* Documentation updated to mention only 1st and 3rd options.

I strongly believe this is the best scenario for all the people out there. But we will have to remove one of the methods when we get down to next MAJOR release (hopefully v5).

**The lesson: have import-ing and require-ing unit tests before migrating to TS!**

PS: There might be a lot of pain when we would need to support _the amazing_ mjs file extension.

**Comment by koresar** [comment]
The v4.1.3 was published. All of these should work now:

```js
const Agenda = require("agenda");
const { Agenda } = require("agenda");
import Agenda from "agenda";
import { Agenda } from "agenda";
```

**Comment by tehsunnliu** [comment]
Hi for me `import { Agenda } from "agenda";` worked, and `import Agenda from "agenda";` still throws this exception.
